# fly.toml app configuration file generated for neo-ark-datingapp on 2023-08-02T14:26:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "neo-ark-datingapp"
primary_region = "mad"

[build]
  image = "neokyuubi/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dvebxsofu"
  CloudinarySettings__ApiKey="294211664547824"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
